Repository Team-PIDA/PIDA_iOS, pull requests merged in 2025-04, with the labels that each got.

#45 지도 마커 오류 수정
  Projects/Core/DesignKit/Resources/Icons.xcassets/empty_result.imageset/Contents.json
  Projects/Core/DesignKit/Resources/Icons.xcassets/empty_result.imageset/wrong_location_24dp_5F6368_FILL0_wght200_GRAD0_opsz24 1.png
  Projects/Core/DesignKit/Resources/Icons.xcassets/empty_result.imageset/wrong_location_24dp_5F6368_FILL0_wght200_GRAD0_opsz24 1@2x.png
  Projects/Core/DesignKit/Resources/Icons.xcassets/empty_result.imageset/wrong_location_24dp_5F6368_FILL0_wght200_GRAD0_opsz24 1@3x.png
  Projects/Core/DesignKit/Sources/Resource+/Image+.swift
  Projects/Features/Map/MapFeature/Sources/MapView/MapReducer.swift
  Projects/Features/Map/MapFeatureInterface/Sources/MapView/MapReducer.swift
  Projects/Features/Map/MapFeatureInterface/Sources/MapView/MapView.swift
  Projects/Features/Map/MapFeatureInterface/Sources/MapView/View/MapViewCoordinator.swift
  Projects/Features/Map/MapFeatureInterface/Sources/MapView/View/MapViewRepresentable.swift
  Projects/Features/Search/SearchFeature/Sources/SearchReducer.swift
  Projects/Features/Search/SearchFeatureInterface/Sources/SearchReducer.swift
  Projects/Features/Search/SearchFeatureInterface/Sources/SearchView.swift
  Projects/PIDA/Sources/PIDAReducer.swift
Labels: HotFix

#47 설정 화면 수정 및 런치스크린 추가
  Projects/Features/Auth/AuthFeature/Sources/AuthReducer.swift
  Projects/Features/Setting/SettingFeature/Sources/SettingReducer.swift
  Projects/Features/Setting/SettingFeatureInterface/Sources/SettingReducer.swift
  Projects/Features/Setting/SettingFeatureInterface/Sources/SettingView.swift
  Projects/PIDA/Resources/LaunchScreen.storyboard
  Projects/PIDA/Resources/Splash Image@3x.png
  Projects/Shared/Utility/Sources/Services/AppVersionService.swift
  Projects/Shared/Utility/Sources/Services/AppleLogin/AppleLoginManager.swift
  Projects/Shared/Utility/Sources/Types/ExternalURL.swift
Labels: Feature

#49 바텀시트 및 검색에 의한 지도 마커 오류 수정
  Projects/Features/Map/MapFeature/Sources/MapView/MapReducer.swift
  Projects/Features/Map/MapFeatureInterface/Sources/MapView/MapReducer.swift
  Projects/Features/Map/MapFeatureInterface/Sources/MapView/MapView.swift
  Projects/Features/Map/MapFeatureInterface/Sources/MapView/View/MapViewCoordinator.swift
  Projects/Features/Map/MapFeatureInterface/Sources/MapView/View/MapViewRepresentable.swift
Labels: HotFix

#54 상세화면 지도 구현
  Projects/Core/DesignKit/Sources/Resource+/BlossomState+.swift
  Projects/Features/FlowerSpotDetail/FlowerSpotDetailFeature/Sources/FlowerSpotDetailReducer.swift
  Projects/Features/FlowerSpotDetail/FlowerSpotDetailFeatureInterface/Sources/DetailMapViewRepresentable.swift
  Projects/Features/FlowerSpotDetail/FlowerSpotDetailFeatureInterface/Sources/FlowerSpotDetailReducer.swift
  Projects/Features/FlowerSpotDetail/FlowerSpotDetailFeatureInterface/Sources/FlowerSpotDetailView.swift
  Projects/Features/Map/MapFeatureInterface/Sources/MapView/View/MapViewRepresentable.swift
  Projects/PIDA/Sources/AppDelegate.swift
  Projects/PIDA/Sources/PIDAApp.swift
Labels: Feature

#57 1차 QA 반영
  Projects/Core/DesignKit/Sources/Component/ResearchButton/ResearchButton.swift
  Projects/Core/DesignKit/Sources/Component/TagView/TagView.swift
  Projects/PIDA/Resources/LaunchScreen.storyboard
  Projects/PIDA/Resources/Splash Image@3x.png
  Projects/PIDA/Resources/SplashImage.png
Labels: QA

#61 Feature/blooming state verify
  Projects/Data/Blooming/BloomingData/Sources/BloomingRepositoryImpl.swift
  Projects/Data/Blooming/BloomingDataInterface/Sources/DTO/VerifyBloomingStateDTO.swift
  Projects/Data/Blooming/BloomingDataInterface/Sources/EndPoint/BloomingEndPoint.swift
  Projects/Domain/Blooming/BloomingDomain/Sources/VerifyBloomingTodayUseCaseImpl.swift
  Projects/Domain/Blooming/BloomingDomainInterface/Sources/BloomingRepository.swift
  Projects/Domain/Blooming/BloomingDomainInterface/Sources/DependencyKeys/VerifyBloomingTodayUseCaseKey.swift
  Projects/Domain/Blooming/BloomingDomainInterface/Sources/Entity/VerifyBloomingStateEntity.swift
  Projects/Domain/Blooming/BloomingDomainInterface/Sources/UseCases/VerifyBloomingTodayUseCase.swift
  Projects/Features/FlowerSpotDetail/FlowerSpotDetailFeature/Sources/FlowerSpotDetailReducer.swift
  Projects/Features/FlowerSpotDetail/FlowerSpotDetailFeatureInterface/Sources/FlowerSpotDetailReducer.swift
  Projects/Features/FlowerSpotDetail/FlowerSpotDetailFeatureInterface/Sources/FlowerSpotDetailView.swift
  Projects/Features/Map/MapFeature/Sources/MapView/MapReducer.swift
  Projects/Features/Map/MapFeatureInterface/Sources/MapView/MapReducer.swift
  Projects/Features/Map/MapFeatureInterface/Sources/MapView/MapView.swift
  Projects/PIDA/Project.swift
  Projects/PIDA/Sources/DependencyRegister.swift
  Projects/PIDA/Sources/PIDAReducer.swift
  Tuist/ProjectDescriptionHelpers/Target+.swift
Labels: Feature

#64 개화 상태 투표 후 마커 업데이트
  Projects/Features/FlowerSpotDetail/FlowerSpotDetailFeatureInterface/Sources/DetailMapViewRepresentable.swift
  Projects/Features/FlowerSpotDetail/FlowerSpotDetailFeatureInterface/Sources/FlowerSpotDetailView.swift
  Projects/Features/Map/MapFeature/Sources/MapView/MapReducer.swift
  Projects/Features/Map/MapFeatureInterface/Sources/MapView/MapReducer.swift
  Projects/Features/Map/MapFeatureInterface/Sources/MapView/MapView.swift
  Projects/Features/Map/MapFeatureInterface/Sources/MapView/View/MapViewCoordinator.swift
  Projects/Features/Map/MapFeatureInterface/Sources/MapView/View/MapViewRepresentable.swift
  Projects/PIDA/Sources/PIDAReducer.swift
Labels: Feature

#65 MapReducer 구조 분리작업
  Projects/Features/Map/MapFeature/Sources/MapView/DetailReducer.swift
  Projects/Features/Map/MapFeature/Sources/MapView/LocationReducer.swift
  Projects/Features/Map/MapFeature/Sources/MapView/MapReducer.swift
  Projects/Features/Map/MapFeatureInterface/Sources/MapView/DetailReducer.swift
  Projects/Features/Map/MapFeatureInterface/Sources/MapView/LocationReducer.swift
  Projects/Features/Map/MapFeatureInterface/Sources/MapView/MapReducer.swift
  Projects/Features/Map/MapFeatureInterface/Sources/MapView/MapView.swift
Labels: Refactoring

#66 지도 줌 레벨 조정
  Projects/Features/Map/MapFeatureInterface/Sources/MapView/View/MapViewRepresentable.swift
Labels: Feature

#71 Refactor/update design system
  Projects/Core/DesignKit/Sources/Component/TagView/Modifier/TagView+.swift
  Projects/Core/DesignKit/Sources/Component/TagView/TagView.swift
  Projects/Core/DesignKit/Sources/Component/Toast/Modifier/ToastView+.swift
  Projects/Core/DesignKit/Sources/Component/Toast/ToastView.swift
Labels: Refactoring

#69 위치 권한 거부 시 얼럿 띄우기
  Projects/Core/DesignKit/Sources/Modifier/AlertType.swift
  Projects/Features/Map/MapFeature/Sources/MapView/LocationReducer.swift
  Projects/Features/Map/MapFeature/Sources/MapView/MapReducer.swift
  Projects/Features/Map/MapFeatureInterface/Sources/MapView/LocationReducer.swift
  Projects/Features/Map/MapFeatureInterface/Sources/MapView/MapReducer.swift
  Projects/Features/Map/MapFeatureInterface/Sources/MapView/MapView.swift
  Projects/Features/Setting/SettingFeature/Sources/SettingReducer.swift
  Projects/Features/Setting/SettingFeatureInterface/Sources/SettingReducer.swift
  Projects/Features/Setting/SettingFeatureInterface/Sources/SettingView.swift
Labels: Feature

#76 [Feature] 개화 정보 바텀시트에 제공되는 TagView 수정 작업
  Projects/Core/DesignKit/Sources/Component/BottomSheet/BottomSheet.swift
  Projects/Core/DesignKit/Sources/Component/TagView/TagCase.swift
  Projects/Core/DesignKit/Sources/Component/TagView/TagView.swift
  Projects/Domain/FlowerSpot/FlowerSpotDomainInterface/Sources/Entity/FlowerSpotListEntity.swift
  Projects/Features/Map/MapFeatureInterface/Sources/MapView/MapView.swift
Labels: Feature

#75 제보하기 추가 및 SettingView 변경사항 적용
  Projects/Core/DesignKit/Resources/Icons.xcassets/feedback.imageset/Contents.json
  Projects/Core/DesignKit/Resources/Icons.xcassets/feedback.imageset/feedback.png
  Projects/Core/DesignKit/Resources/Icons.xcassets/feedback.imageset/feedback@2x.png
  Projects/Core/DesignKit/Resources/Icons.xcassets/feedback.imageset/feedback@3x.png
  Projects/Core/DesignKit/Sources/Component/Icon/IconSize.swift
  Projects/Core/DesignKit/Sources/Resource+/Image+.swift
  Projects/Features/Map/MapFeature/Sources/MapView/LocationReducer.swift
  Projects/Features/Map/MapFeature/Sources/MapView/MapReducer.swift
  Projects/Features/Map/MapFeatureInterface/Sources/MapView/LocationReducer.swift
  Projects/Features/Map/MapFeatureInterface/Sources/MapView/MapReducer.swift
  Projects/Features/Map/MapFeatureInterface/Sources/MapView/MapView.swift
  Projects/Features/Setting/SettingFeature/Sources/SettingReducer.swift
  Projects/Features/Setting/SettingFeatureInterface/Sources/SettingList/SettingItem.swift
  Projects/Features/Setting/SettingFeatureInterface/Sources/SettingList/SettingItemView.swift
  Projects/Features/Setting/SettingFeatureInterface/Sources/SettingReducer.swift
  Projects/Features/Setting/SettingFeatureInterface/Sources/SettingView.swift
  Projects/Shared/Utility/Sources/Types/ExternalURL.swift
Labels: Feature

#80 SettingView QA 사항 적용
  Projects/Core/Networker/Sources/Implement/Networker.swift
  Projects/Core/Networker/Sources/Interface/ErrorResponse.swift
  Projects/Features/Auth/AuthFeature/Sources/SignUpReducer.swift
  Projects/Features/Auth/AuthFeatureInterface/Sources/SignUp/SignUpReducer.swift
  Projects/Features/Auth/AuthFeatureInterface/Sources/SignUp/SignUpView.swift
  Projects/Features/Setting/SettingFeature/Sources/ProfileUpdateReducer.swift
  Projects/Features/Setting/SettingFeatureInterface/Sources/SettingView.swift
  Projects/Features/Setting/SettingFeatureInterface/Sources/Update/ProfileUpdateReducer.swift
  Projects/Shared/Utility/Sources/Errors/ErrorClassName.swift
  Projects/Shared/Utility/Sources/Errors/NetworkError.swift
  Projects/Shared/Utility/Sources/Types/ExternalURL.swift
  Projects/Shared/Utility/Sources/Types/NicknameValidType.swift
Labels: QA
